exec(open('league.py').read())
exec(open('gurobimodel.py').read())
exec(open('scipmodel.py').read())
exec(open('divisions.py').read())
exec(open('plot_teams.py').read())
exec(open('results.py').read())